### ISSUE TITLE
Shows error when running in 1.19.3 minecraft version and working fine when running in 1.17.1

### ISSUE THREAD

**Issue by siddvish21** [etiaro/mineflayer-antiafk#11]
When i run it in 1.17.1 it works perfectly fine with no error but when i run it will 1.19.3 then it shows this error:
        bot.autoEat.foodsByName = require('minecraft-data')(bot.version).foodsByName
                                                                        ^

TypeError: Cannot read properties of null (reading 'foodsByName')
    at EventEmitter.<anonymous> (C:\Users\Siddharth\Documents\ws\Minecraft-Bot\node_modules\mineflayer-antiafk\node_modules\mineflayer-auto-eat\index.js:27:73)
    at Object.onceWrapper (node:events:627:28)
    at EventEmitter.emit (node:events:525:35)
    at Client.<anonymous> (C:\Users\Siddharth\Documents\ws\Minecraft-Bot\node_modules\mineflayer\lib\plugins\health.js:13:11)
    at Object.onceWrapper (node:events:628:26)
    at Client.emit (node:events:525:35)
    at FullPacketParser.<anonymous> (C:\Users\Siddharth\Documents\ws\Minecraft-Bot\node_modules\minecraft-protocol\src\client.js:91:12)
    at FullPacketParser.emit (node:events:513:28)
    at addChunk (C:\Users\Siddharth\Documents\ws\Minecraft-Bot\node_modules\readable-stream\lib\_stream_readable.js:298:12)
    at readableAddChunk (C:\Users\Siddharth\Documents\ws\Minecraft-Bot\node_modules\readable-stream\lib\_stream_readable.js:280:11)

**Comment by jacobjake1** [comment]
bump pls fix
